[workspace]
authors = ["llql1211 <1390116067@qq.com>"]
channels = ["conda-forge"]
name = "LLMTranslator"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.6,<3.15"
pyautogui = ">=0.9.54,<0.10"
pynput = ">=1.8.2,<2"
requests = ">=2.34.2,<3"
